project:
  type: website
  output-dir: _site

website:
  title: Science at Fishbourne
  site-url: https://scienceatfishbourne.org
  open-graph: true
  favicon: /images/microscope.svg
  google-analytics: "G-5X0PRJMD0B"
  llms-txt: true
  navbar:
    title: false
    logo: "/images/textlogo.png"
    left:
      - href: next/next.qmd
        text: Next Talk
      - previous.qmd
      - news.qmd
      - subscribe.qmd
      - contact.qmd
      - location.qmd
    right:
      - about.qmd
  announcement:
    icon: info-circle
    dismissable: true
    content: "How do you feel about an increase in meeting fees versus a change of venue (and maybe day and/or time)? Let us know by filling out our [venue survey](https://forms.gle/kRWZfoznCxqsnrJW7)"
    type: info
    position: below-navbar

format:
  html:
    author-title: Speaker(s)
    published-title: Presentation Date
    theme:
      - flatly
      - custom.scss
    css: styles.css
    title-block-banner: true
