#!/bin/bash
# Generate a placeholder poster for Science at Fishbourne

cmd=magick
hash $cmd 2>/dev/null || cmd=convert

nextdate="18 Aug 2025"

text="Science at\nFishbourne\n\nNext talk\n${nextdate}"

echo -e "Generating placeholder.jpg poster with text:\n${text}"

$cmd -background lightblue -fill red  -font PT-Sans-Bold \
          -size 540x780  -pointsize 60  -gravity center \
          label:"${text}"     placeholder.jpg
